In [1]:
import importlib
import sys
import torch
import numpy as np

sys.path.insert(0, '..')
sys.path.insert(0, '../..')
sys.path.insert(0, '../../..')

In [2]:
import event_log_loader.new_event_log_loader
importlib.reload(event_log_loader.new_event_log_loader)
from event_log_loader.new_event_log_loader import EventLogLoader

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

np.random.seed(17)

event_log_location = '../../../../../../evaluation_results/data/helpdesk.csv'
result_name = 'helpdesk_all_lognormal'

event_log_properties = {
    'case_name' : 'CaseID',
    'concept_name' : 'Activity',
    'timestamp_name' : 'CompleteTimestamp',
    'date_format' : '%Y/%m/%d %H:%M:%S.%f',
    'time_since_case_start_column' : 'case_elapsed_time',
    'time_since_last_event_column' : 'event_elapsed_time',
    'day_in_week_column' : 'day_in_week',
    'seconds_in_day_column' : 'seconds_in_day',
    'min_suffix_size' : 5,
    'train_validation_size' : 0.15,
    'test_validation_size' : 0.2,
    'window_size' : 'auto',
    'categorical_columns' : ['Activity', 'Resource', 'VariantIndex', 'seriousness', 'customer', 'product', 'responsible_section', 'seriousness_2', 'service_level', 'service_type', 'support_section', 'workgroup'],
    'continuous_columns' : ['day_in_week', 'seconds_in_day'],
    'continuous_positive_columns' : ['case_elapsed_time', 'event_elapsed_time'],
}

# Henryk attributes:
## Activity, Resource

# 1) loads event log
# 2) adds EOS to cases
# 3) normalizes numerical features
# 4) imputes features (replaces n.a. categories with a new class for categorical features and average values for numerical featues)
event_log_loader = EventLogLoader(event_log_location, event_log_properties)

Positive Standardization
min,25%,50%,75%,max: [ 0.         13.76077271 13.96060085 13.96060085 15.21700668]
Mean:  [11.911889]
Std:  [4.635072]
Positive Standardization
min,25%,50%,75%,max: [ 1.79175949 13.77812481 13.77812481 13.77812481 15.2113142 ]
Mean:  [12.894316]
Std:  [2.6312397]


/home/LordKunkler/.local/share/virtualenvs/PrimePPM-tDGhFIeG/lib/python3.13/site-packages/sklearn/preprocessing/_function_transformer.py:210: UserWarning: The provided functions are not strictly inverse of each other. If you are sure you want to proceed regardless, set 'check_inverse=False'.
  warnings.warn(
/home/LordKunkler/.local/share/virtualenvs/PrimePPM-tDGhFIeG/lib/python3.13/site-packages/sklearn/preprocessing/_function_transformer.py:210: UserWarning: The provided functions are not strictly inverse of each other. If you are sure you want to proceed regardless, set 'check_inverse=False'.
  warnings.warn(


In [3]:
print(event_log_loader.encoder_decoder.window_size)

18


In [4]:
train_dataset = event_log_loader.get_dataset('train')
torch.save(train_dataset, '../../../../encoded_data/log_stand/'+result_name+'_'+str(event_log_loader.encoder_decoder.min_suffix_size)+'_train.pkl')
print(train_dataset.all_categories)

categorical tensors:   0%|          | 0/12 [00:00<?, ?it/s]

Activity:   0%|          | 0/2977 [00:00<?, ?it/s]

Resource:   0%|          | 0/2977 [00:00<?, ?it/s]

VariantIndex:   0%|          | 0/2977 [00:00<?, ?it/s]

seriousness:   0%|          | 0/2977 [00:00<?, ?it/s]

customer:   0%|          | 0/2977 [00:00<?, ?it/s]

product:   0%|          | 0/2977 [00:00<?, ?it/s]

responsible_section:   0%|          | 0/2977 [00:00<?, ?it/s]

seriousness_2:   0%|          | 0/2977 [00:00<?, ?it/s]

service_level:   0%|          | 0/2977 [00:00<?, ?it/s]

service_type:   0%|          | 0/2977 [00:00<?, ?it/s]

support_section:   0%|          | 0/2977 [00:00<?, ?it/s]

workgroup:   0%|          | 0/2977 [00:00<?, ?it/s]

continouous tensors:   0%|          | 0/4 [00:00<?, ?it/s]

day_in_week:   0%|          | 0/2977 [00:00<?, ?it/s]

seconds_in_day:   0%|          | 0/2977 [00:00<?, ?it/s]

case_elapsed_time:   0%|          | 0/2977 [00:00<?, ?it/s]

Positive Standardization
min,25%,50%,75%,max: [ 0.         13.96060085 13.96060085 14.9776001  15.31714916]
Mean:  [12.786152]
Std:  [4.550863]
Positive Standardization
min,25%,50%,75%,max: [ 0.         13.89290118 13.96060085 13.96060085 15.24048805]
Mean:  [12.763235]
Std:  [4.2783303]
Positive Standardization
min,25%,50%,75%,max: [ 0.          5.17841005 13.96060085 13.96060085 15.15105057]
Mean:  [10.24837]
Std:  [5.775896]
Positive Standardization
min,25%,50%,75%,max: [ 0.         13.96060085 13.96060085 14.17794991 14.91312695]
Mean:  [12.582546]
Std:  [4.458604]
Positive Standardization
min,25%,50%,75%,max: [ 0.         12.01959896 13.96060085 13.96060085 14.80082798]
Mean:  [12.068697]
Std:  [4.359184]
Positive Standardization
min,25%,50%,75%,max: [ 0.         13.96060085 13.96060085 14.30354977 15.12754726]
Mean:  [12.65916]
Std:  [4.4929357]
Positive Standardization
min,25%,50%,75%,max: [ 0.         13.18135452 13.96060085 13.96060085 14.80076408]
Mean:  [12.308387]
Std:  [4.

event_elapsed_time:   0%|          | 0/2977 [00:00<?, ?it/s]

Positive Standardization
min,25%,50%,75%,max: [ 2.07944155 13.77812481 13.77812481 13.77812481 14.9776001 ]
Mean:  [12.644202]
Std:  [3.7536986]
Positive Standardization
min,25%,50%,75%,max: [ 9.88486481 13.77812481 13.77812481 13.83321452 14.40628719]
Mean:  [13.488629]
Std:  [1.2168566]
Positive Standardization
min,25%,50%,75%,max: [ 1.94591022 13.20860529 13.77812481 13.77812481 15.02484226]
Mean:  [11.460417]
Std:  [4.7792873]
Positive Standardization
min,25%,50%,75%,max: [12.49787998 13.77812481 13.77812481 13.77812481 14.17794991]
Mean:  [13.712955]
Std:  [0.45301962]
Positive Standardization
min,25%,50%,75%,max: [ 8.30918407 13.77812481 13.77812481 13.77812481 14.73686409]
Mean:  [13.078847]
Std:  [1.8137661]
Positive Standardization
min,25%,50%,75%,max: [13.57800674 13.77812481 13.77812481 13.77812481 14.30354977]
Mean:  [13.847234]
Std:  [0.20032014]
Positive Standardization
min,25%,50%,75%,max: [11.43191051 13.77812481 13.77812481 13.77812481 14.58009815]
Mean:  [13.519012]
S

In [5]:
test_dataset = event_log_loader.get_dataset('test')
torch.save(test_dataset, '../../../../encoded_data/log_stand/'+result_name+'_'+str(event_log_loader.encoder_decoder.min_suffix_size)+'_test.pkl')

categorical tensors:   0%|          | 0/12 [00:00<?, ?it/s]

Activity:   0%|          | 0/916 [00:00<?, ?it/s]

Resource:   0%|          | 0/916 [00:00<?, ?it/s]

VariantIndex:   0%|          | 0/916 [00:00<?, ?it/s]

seriousness:   0%|          | 0/916 [00:00<?, ?it/s]

customer:   0%|          | 0/916 [00:00<?, ?it/s]

product:   0%|          | 0/916 [00:00<?, ?it/s]

responsible_section:   0%|          | 0/916 [00:00<?, ?it/s]

seriousness_2:   0%|          | 0/916 [00:00<?, ?it/s]

service_level:   0%|          | 0/916 [00:00<?, ?it/s]

service_type:   0%|          | 0/916 [00:00<?, ?it/s]

support_section:   0%|          | 0/916 [00:00<?, ?it/s]

workgroup:   0%|          | 0/916 [00:00<?, ?it/s]

continouous tensors:   0%|          | 0/4 [00:00<?, ?it/s]

day_in_week:   0%|          | 0/916 [00:00<?, ?it/s]

seconds_in_day:   0%|          | 0/916 [00:00<?, ?it/s]

case_elapsed_time:   0%|          | 0/916 [00:00<?, ?it/s]

Positive Standardization
min,25%,50%,75%,max: [ 0.         10.1686554  13.96060085 13.96060085 15.44437408]
Mean:  [11.158519]
Std:  [4.9544115]
Positive Standardization
min,25%,50%,75%,max: [ 0.         11.32608986 13.96060085 13.96060085 15.19542503]
Mean:  [11.076869]
Std:  [5.171919]
Positive Standardization
min,25%,50%,75%,max: [ 0.         13.34519482 13.96060085 13.96060085 15.29874611]
Mean:  [11.543432]
Std:  [5.2507925]
Positive Standardization
min,25%,50%,75%,max: [ 0.          9.43252373 13.96060085 13.96060085 14.80091286]
Mean:  [11.080755]
Std:  [4.8288865]
Positive Standardization
min,25%,50%,75%,max: [ 0.         11.53314972 13.96060085 13.96060085 14.86337948]
Mean:  [11.556834]
Std:  [4.5632434]
Positive Standardization
min,25%,50%,75%,max: [ 0.         11.66867161 13.96060085 13.96060085 15.15003109]
Mean:  [11.03664]
Std:  [5.2835174]
Positive Standardization
min,25%,50%,75%,max: [ 0.         13.7422061  13.96060085 13.96060085 14.84164619]
Mean:  [12.574179]
Std: 

event_elapsed_time:   0%|          | 0/916 [00:00<?, ?it/s]

Positive Standardization
min,25%,50%,75%,max: [ 5.01063538 13.77812481 13.77812481 13.77812481 15.43924618]
Mean:  [12.58684]
Std:  [2.980034]
Positive Standardization
min,25%,50%,75%,max: [ 3.36729574 13.77812481 13.77812481 13.77812481 15.17433262]
Mean:  [12.504014]
Std:  [3.3621864]
Positive Standardization
min,25%,50%,75%,max: [ 2.30258512 13.77812481 13.77812481 13.77812481 14.69900799]
Mean:  [12.701719]
Std:  [3.4862654]
Positive Standardization
min,25%,50%,75%,max: [ 5.69035959 13.77812481 13.77812481 13.77812481 14.79623985]
Mean:  [12.507107]
Std:  [2.8087506]
Positive Standardization
min,25%,50%,75%,max: [ 7.81197357 13.77812481 13.77812481 13.77812481 14.82693863]
Mean:  [12.97959]
Std:  [2.0029576]
Positive Standardization
min,25%,50%,75%,max: [ 2.70805025 13.77812481 13.77812481 13.77812481 15.118783  ]
Mean:  [12.462681]
Std:  [3.5468404]
Positive Standardization
min,25%,50%,75%,max: [12.66964626 13.45984674 13.77812481 13.77812481 14.07480907]
Mean:  [13.597755]
Std:  

In [6]:
val_dataset = event_log_loader.get_dataset('val')
torch.save(val_dataset, '../../../../encoded_data/log_stand/'+result_name+'_'+str(event_log_loader.encoder_decoder.min_suffix_size)+'_val.pkl')

categorical tensors:   0%|          | 0/12 [00:00<?, ?it/s]

Activity:   0%|          | 0/687 [00:00<?, ?it/s]

Resource:   0%|          | 0/687 [00:00<?, ?it/s]

VariantIndex:   0%|          | 0/687 [00:00<?, ?it/s]

seriousness:   0%|          | 0/687 [00:00<?, ?it/s]

customer:   0%|          | 0/687 [00:00<?, ?it/s]

product:   0%|          | 0/687 [00:00<?, ?it/s]

responsible_section:   0%|          | 0/687 [00:00<?, ?it/s]

seriousness_2:   0%|          | 0/687 [00:00<?, ?it/s]

service_level:   0%|          | 0/687 [00:00<?, ?it/s]

service_type:   0%|          | 0/687 [00:00<?, ?it/s]

support_section:   0%|          | 0/687 [00:00<?, ?it/s]

workgroup:   0%|          | 0/687 [00:00<?, ?it/s]

continouous tensors:   0%|          | 0/4 [00:00<?, ?it/s]

day_in_week:   0%|          | 0/687 [00:00<?, ?it/s]

seconds_in_day:   0%|          | 0/687 [00:00<?, ?it/s]

case_elapsed_time:   0%|          | 0/687 [00:00<?, ?it/s]

Positive Standardization
min,25%,50%,75%,max: [ 0.         12.84136224 13.96060085 13.96060085 14.79813671]
Mean:  [11.500776]
Std:  [4.903582]
Positive Standardization
min,25%,50%,75%,max: [ 0.         13.96060085 13.96060085 13.96060085 15.42725182]
Mean:  [11.825433]
Std:  [4.8138847]
Positive Standardization
min,25%,50%,75%,max: [ 0.         13.48795843 13.96060085 13.96060085 15.08887672]
Mean:  [12.536563]
Std:  [4.2292743]
Positive Standardization
min,25%,50%,75%,max: [ 0.         12.990798   13.96060085 14.05797386 14.80908489]
Mean:  [12.451336]
Std:  [4.024497]
Positive Standardization
min,25%,50%,75%,max: [ 0.         13.96060085 13.96060085 14.24048138 14.85708141]
Mean:  [12.738641]
Std:  [4.254503]
Positive Standardization
min,25%,50%,75%,max: [ 0.         11.86772037 13.96060085 13.96060085 14.97783566]
Mean:  [12.061046]
Std:  [4.16024]
Positive Standardization
min,25%,50%,75%,max: [ 0.         11.48859215 13.57258987 13.96060085 15.03230858]
Mean:  [11.634312]
Std:  [3

event_elapsed_time:   0%|          | 0/687 [00:00<?, ?it/s]

Positive Standardization
min,25%,50%,75%,max: [ 3.80666256 13.77812481 13.77812481 13.77812481 14.07757759]
Mean:  [12.694266]
Std:  [2.991805]
Positive Standardization
min,25%,50%,75%,max: [ 6.72982407 13.77812481 13.77812481 13.77812481 14.94356823]
Mean:  [13.201168]
Std:  [2.3218133]
Positive Standardization
min,25%,50%,75%,max: [12.50503254 13.77812481 13.77812481 13.77812481 14.32305431]
Mean:  [13.632566]
Std:  [0.5331622]
Positive Standardization
min,25%,50%,75%,max: [ 3.40119743 12.89947271 13.77812481 13.77812481 14.07480907]
Mean:  [11.918206]
Std:  [3.712327]
Positive Standardization
min,25%,50%,75%,max: [ 7.13089895 13.77812481 13.77812481 13.77812481 14.23986912]
Mean:  [12.707466]
Std:  [2.3713877]
Positive Standardization
min,25%,50%,75%,max: [ 8.91152954 12.74863291 13.77812481 13.77812481 14.86195564]
Mean:  [13.03435]
Std:  [1.6254106]
Positive Standardization
min,25%,50%,75%,max: [ 3.17805386 11.15118027 13.77812481 13.77812481 14.76795101]
Mean:  [11.808239]
Std:  

In [7]:
val_dataset[1337]

((tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1, 13, 11, 13, 15, 13, 11]),
  tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 23, 23, 23, 23,  5,  5,  5]),
  tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 79, 79, 79, 79, 79, 79, 79]),
  tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2]),
  tensor([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0, 351, 351, 351,
          351, 351, 351, 351]),
  tensor([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 16, 16, 16, 16, 16, 16, 16]),
  tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2]),
  tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 3, 3, 3, 3, 3]),
  tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 4, 4, 4, 4, 4]),
  tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2]),
  tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2]),
  tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 2])),
 (tensor([ 0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,  0.0000,
       